### ISSUE TITLE
Вывести алерт при клике на клетку со студентом

### ISSUE THREAD

**Issue by davojta** [rss-com-lab/mentor-dashboard#15]
Нужно вывести алерт со следующими данными
- github mentor
- github student
- task name

**Comment by petriken** [comment]
Получается кликаем на ячейку с оценкой у любого студента и выползает алерт, так? Ссылка на ПР, которая вылазила раньше, уже не актуальна?

**Comment by davojta** [comment]
Получается что надо либо ссылку на ПР если оценка уже нет
если оценки нету в клетке - надо алерт

**Comment by uniorunr** [comment]
@davojta @petriken Шит, я уже смержил. А там алерт выводится всегда. И когда есть отметка и когда нет.

**Comment by petriken** [comment]
> Получается что надо либо ссылку на ПР если оценка уже нет
> если оценки нету в клетке - надо алерт

принято, сделаю, чет я сразу не подумал...

**Comment by davojta** [comment]
@uniorunr ничего страшного )
Петр доделает )

**Comment by petriken** [comment]
Доделал уже )
